context:
  version: "15.0.3"

package:
  name: eslint_d
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/eslint_d/-/eslint_d-${{ version }}.tgz
  sha256: 2d635c2a6037f2840cfb07804b729555222bfaa642dfbd1d3823447ece593e85

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - eslint_d --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Speed up eslint to accelerate your development workflow
  homepage: https://github.com/mantoni/eslint_d.js
  repository: https://github.com/mantoni/eslint_d.js

extra:
  recipe-maintainers:
    - danielnachun
